### ISSUE TITLE
Notice: Undefined property: AppBundle\Entity\ArticleTranslation::$currentLocale

### ISSUE THREAD

**Issue by NTsvetkov** [Prezent/doctrine-translatable-bundle#15]
Hi,

Please, help the noob to use your package.

I think I did everything according to the manual. The only problem for me is the listener. Where I can find more information about how to make it?

**Comment by sandermarechal** [comment]
Did you read only the bundle documentation or did you also read the documentation of the (standalone) library? https://github.com/Prezent/doctrine-translatable/blob/master/doc/index.md

Take a look at the "Getting Started" section of that documentation. It explains the changes you need to make to your own entities, and that you need to implement fields like `$currentLocale` yourself. It also includes the Doctrine listener you need.
