### ISSUE TITLE
Symfony 3.4 / Symfony 4 / Sonata 4.x

### ISSUE THREAD

**Issue by jayesbe** [Prezent/doctrine-translatable-bundle#19]
Looks like there is an upstream function signature change in Sonata that is now bring the installation of this bundle related to using Symfony 4 and Sonata 4.x branches.

Looks like this bundle depends on Sonata in the Filter/TranslatableFilter.php

Will you be branching?

**Comment by sandermarechal** [comment]
Sonata 4.x is not out yet. It's not even in RC stage. When it hits RC I can make this bundle compatible. For now, I updated this bundle to NOT load the sonata integration when the function signature is not compatible.
