### ISSUE TITLE
Release 1.0.4 is broken (Undefined variable: container)

### ISSUE THREAD

**Issue by PetrHeinz** [Prezent/doctrine-translatable-bundle#22]
There is an undefined variable `$container` in `PrezentDoctrineTranslatableExtension::loadSonata()` which triggers an error when the bundle is registered: https://github.com/Prezent/doctrine-translatable-bundle/blob/1.0.4/DependencyInjection/PrezentDoctrineTranslatableExtension.php#L45

```
In PrezentDoctrineTranslatableExtension.php line 45:
                                                             
  [Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Undefined variable: container  
```

Fixed in #21, I'm creating this issue just for transparency - so it's clear what is happening.

**Comment by rjbijl** [comment]
fixed in tag 1.0.5
