### ISSUE TITLE
Missing TranslatableListener

### ISSUE THREAD

**Issue by BarthyB** [Prezent/doctrine-translatable-bundle#23]
## The problem

I query entities like in the following controller action:

```
    /**
     * @param int $id
     * @param EntityManagerInterface $entityManager
     * @param SerializerInterface $serializer
     * @return JsonResponse
     * @Route("/project/{id}", name="project_show")
     */
    public function projectShow(int $id, EntityManagerInterface $entityManager, SerializerInterface $serializer) {
        $project = $entityManager->getRepository('App:Project')->findOneBy([
            'id' => $id
        ]);

        return new JsonResponse($serializer->serialize($project, 'json'));
    }
```
This returns an object of type `Project` with a property of `translations` with a value of `null`.

### Debugging Event Listeners
The command `php bin/console debug:event-dispatcher` shows that the `LocaleListener` is active, but shows no trace of the `TranslatableListener`.
The profiler's "Events" section reflects and confirm those findings.

### Debugging the Container
The command `php bin/console debug:container` shows the following:

| Name                                           | Service                                                          |
|------------------------------------------------|------------------------------------------------------------------|
| prezent_doctrine_translatable.driver_chain     | Metadata\Driver\DriverChain                                      |
| prezent_doctrine_translatable.listener         | Prezent\Doctrine\Translatable\EventListener\TranslatableListener |
| prezent_doctrine_translatable.listener.locale  | Prezent\Doctrine\TranslatableBundle\EventListener\LocaleListener |
| prezent_doctrine_translatable.metadata_factory | Metadata\MetadataFactory                                         |

## Things I Tried
- Configuring the listener inside my `services.yaml`
- Finding the Listener classes in `app/cache/[env]/ProjectContainer` as you mentioned in #3 and #13 . The cache layout may have changed with Symfony 4, but both listener class names can be found using a recursive search in the cache directory.

## Notes
- I also use `stof/doctrine-extensions-bundle` and hence the `gedmo/doctrine-extensions` for `TimeStampable` and `Softdeleteable` behaviour. Could there be any clash?
- I can post the entire entity mapping if needed. I have used the bundle in Symfony 3 projects before and truly believe that the problem does not reside there.
- The Bundle was not automatically added to the `Kernel.php` file upon installation via composer. I added it manually.

## Versions
| Module                            | Version |
|--------------------------------------|---------|
| Symfony                              | 4.1.0   |
| php                                  | 7.2.6   |
| prezent/doctrine-translatable        | 1.2.1   |
| prezent/doctrine-translatable-bundle | 1.0.5   |

*What can I do? Thanks in advance for you help.*

**Comment by sandermarechal** [comment]
> The command php bin/console debug:event-dispatcher shows that the LocaleListener is active, but shows no trace of the TranslatableListener. The profiler's "Events" section reflects and confirm those findings.

That is expected. The `TranslatableListener` is a Doctrine listener, not a Symfony listener. Doctrine has it's own event manager.

> I also use stof/doctrine-extensions-bundle and hence the gedmo/doctrine-extensions for TimeStampable and Softdeleteable behaviour. Could there be any clash?

Not that I know of. I have combined this translatable bundle with stof's extensions many times.

A few things come to mind:

1. What is your entity manager called? Out of the box, the `TranslatableListener` is only configured for the `default` entity manager. If you use multiple named entity managers (or just changed the name of the default one) then the listener may not be configured.

2. What is your serializer mapping? Are you using the Symfony serializer or JMS serializer? Translations are just plain one-to-many doctrine relations, nothing magic (except for a bit of autoconfiguration). You should configure your serializer to serialize the relationship when it serializes the entity.

3. If you do something like this in your controller, does it show the translation?

```php
dump($project->getName()); // Or whatever field is translated
```

**Comment by BarthyB** [comment]
> What is your entity manager called?

~~I haven't touched the doctrine config, so I have only one entity manager without an explicit name.
I have tried explicitly naming the manager 'default' and using the `default_entity_manager: default` option, without success.~~

> What is your serializer mapping?

~~It's the Symfony serializer, but I don't think that this is the source of the problem, since I have checked the result from the entity manage. The `translations` association returns a `null` value.~~

## Wait a second

I went to to dump the `$project` variable like *I have done multiple times yesterday* and found that everything works as it is supposed to.

It is possible that my 3 a.m. brain confused the `currentTranslation` (which was `null`) with the actual `translations`. [Shame on me…](https://media.giphy.com/media/P8WZZ0NYdbXAA/giphy.gif)

*Again, thanks for your help and sorry for wasting you time.*

**Comment by sandermarechal** [comment]
No problem :-)
