### ISSUE TITLE
A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.

### ISSUE THREAD

**Issue by djin1989** [Prezent/doctrine-translatable-bundle#24]
A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.
It happens here:
DependencyInjection/Configuration.php

**Comment by sandermarechal** [comment]
Fixed, thanks!

**Comment by boris-brtan** [comment]
Are you sure? what about BC ?

**Comment by sandermarechal** [comment]
Whoops, you are right. I checked Symfony 2.8 but I mistook the `root()` function for the constructor. Reopening

**Comment by sandermarechal** [comment]
...and fixed, thanks!
