### ISSUE TITLE
Symfony <4.2 incompatibility

### ISSUE THREAD

**Issue by vitek-rostislav** [Prezent/doctrine-translatable-bundle#25]
In the `1.0.6` patch version, after #24 has been closed, you have introduced a BC break (https://github.com/Prezent/doctrine-translatable-bundle/commit/80afed0cf2b2de8a87573f3042e396a5ceaa65dd). The change is not compatible with the older versions of Symfony as there was no constructor nor `getRootNode()` method in [`TreeBuilder`](https://github.com/symfony/symfony/blob/3.4/src/Symfony/Component/Config/Definition/Builder/TreeBuilder.php) until `4.2` release :disappointed: 

The change has broken our framework (we are using caret constraints in our `composer.json`), see https://travis-ci.org/shopsys/shopsys/jobs/541357267

**Comment by sandermarechal** [comment]
Fixed, thanks for the report!
